### ISSUE TITLE
Code Won't Run: 'Get List Error'

### ISSUE THREAD

**Issue by GentlemanGamer94** [wwared/jsrl-get#2]
Here's the issue that came up when I tried to run it:
---
C:\Users\admin\Downloads\jsrl-get-master>jsrl-get.pl
Downloading both songs and videos. You can choose by passing -s or -v respectively as flags.
If you want to print info when an existing song is skipped, use -i.
** GET https://jetsetradio.live/audioplayer/audio/~list.js ==> 404 Not Found (1s)
Error getting the list for 'https://jetsetradio.live/audioplayer/audio/~list.js' at C:\Users\admin\Downloads\jsrl-get-master\jsrl-get.pl line 34.
---
![image](https://user-images.githubusercontent.com/21327190/38955216-f7d75762-4321-11e8-97c7-35fd251bab2e.png)

Would you be able to fix and reupload if you get the chance?

**Comment by wwared** [comment]
I don't look at this repository often, so thanks for the report (and sorry for ignoring it for so long). It should be fixed now
